# Generated by Django 3.0.7 on 2023-04-03 00:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20230319_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Wind Deflector', 'Wind Deflector')], max_length=149),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('AC', 'Accra Central'), ('TD', 'Tudu'), ('LAZ', 'Lapaz'), ('AM', 'Amasaman'), ('SR', 'Spintex Road'), ('EA', 'East Airport'), ('DZ', 'Dzorwulu'), ('LEG', 'Legon'), ('NK', 'Kaneshie North'), ('NL', 'North Legon'), ('AB', 'Abeka'), ('ACM', 'Achimota'), ('TS', 'Teshie'), ('NUN', 'Nungua'), ('MAL', 'Mallam'), ('AD', 'Adabraka'), ('OS', 'Osu'), ('MAD', 'Madina'), ('AD', 'Adenta'), ('DOM', 'Dome'), ('ABKM', 'Ablekumah'), ('TCM1', 'Tema Comm.1'), ('TCM2', 'Tema Comm.2'), ('TCM3', 'Tema Comm.3'), ('TCM4', 'Tema Comm.4'), ('TCM5', 'Tema Comm.5'), ('TCM6', 'Tema Comm.6'), ('TCM7', 'Tema Comm.7'), ('TCM8', 'Tema Comm.8'), ('TCM9', 'Tema Comm.9'), ('TCM10', 'Tema Comm.10'), ('TCM15', 'Tema Comm.15'), ('TCMA20', 'Tema Comm.20'), ('TCM15', 'Tema Comm.25')], max_length=100),
        ),
    ]
